server:
  port: 8086

spring:
  application:
    name: employee-manage-api
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 9850432264
    url: jdbc:postgresql://localhost:5432/employeeSpring

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

